services:
  ec-1:
    environment:
      BASE_APP_URL: https://ec:4173/
      TRAFFICLIGHT_URL: http://trafficlight:5000
    build: ../
    restart: always
    extra_hosts:
      - "ec:host-gateway"
      - "trafficlight:host-gateway"
    volumes:
    - source: ./ec-store-1
      target: /video
      type: bind
  ec-2:
    environment:
      BASE_APP_URL: https://ec:4173/
      TRAFFICLIGHT_URL: http://trafficlight:5000
    build: ../
    restart: always
    extra_hosts:
      - "ec:host-gateway"
      - "trafficlight:host-gateway"
    volumes:
    - source: ./ec-store-2
      target: /video
      type: bind
version: '3.9'

